sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
    - libyajl-dev
    - libgeoip-dev
    - liblmdb-dev
    - apache2
    - apache2-bin
    - apache2-data
    - apache2-dbg
    - apache2-dev
    - apache2-mpm-prefork
    - libwww-perl

env:
  - VER_APACHE=2.2.34
  - VER_APACHE=2.4.29

before_script:
  - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
  - cd ..
  - curl https://archive.apache.org/dist/httpd/httpd-${VER_APACHE}.tar.gz > httpd-${VER_APACHE}.tar.gz
  - tar xvzf httpd-${VER_APACHE}.tar.gz
  - cd httpd-${VER_APACHE}
  - ./configure  --with-mpm=worker
  - make -j4
  - sudo make install
  - cd -
  - sudo cpanm --quiet --notest --skip-satisfied CGI::Cookie
  - sudo cpanm --quiet --notest --skip-satisfied Apache::TestRun
  - git clone https://github.com/SpiderLabs/CeleoWAF.git
  - cd CeleoWAF
  - git checkout v3/master
  - git submodule init
  - git submodule update
  - ./build.sh
  - ./configure --without-lmdb
  - make
  - sudo make install
  - pwd
  - cd -
  - cd CeleoWAF-apache
  - ./autogen.sh
  - export PATH="/usr/local/apache2/bin/:$PATH"
  - ls -la /usr/local/apache2/bin/
  - ls -la /usr/local/apache2/include/
  - ./configure --with-apxs=/usr/local/apache2/bin/apxs --with-libceleowaf=/usr/local/celeowaf
  - make
  - sudo make install
  - pwd

script:
    - t/TEST -apxs /usr/local/apache2/bin/apxs

